logger:
  level: "INFO"

storage:
  type: SQL
  addr: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"

rabbitmq:
  addr: "${RABBITMQ_HOST}:${RABBITMQ_PORT}"
  queue: "calendar_events"
  username: "${RABBITMQ_USER}"
  password: "${RABBITMQ_PASS}"