logger:
  level: "INFO"

server:
  addr: "0.0.0.0:${CALENDAR_HTTP_PORT}"

grpc:
  addr: "0.0.0.0:${CALENDAR_GRPC_PORT}"

storage:
  type: SQL
  addr: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}"