logger:
  level: "INFO"

storage:
  type: SQL
  addr: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}"

rabbitmq:
  addr: "${RABBITMQ_HOST}:${RABBITMQ_PORT}"
  queue: "${RABBITMQ_QUEUE}"
  username: "${RABBITMQ_USER}"
  password: "${RABBITMQ_PASS}"