name: calendar-tests

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ..
      dockerfile: build/Dockerfile.migrations
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "sleep 2 && goose -dir /migrations postgres \"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}\" up"]
    volumes:
      - ../migrations:/migrations

  calendar:
    build:
      context: ..
      dockerfile: build/Dockerfile.calendar
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "${CALENDAR_HTTP_PORT}:${CALENDAR_HTTP_PORT}"
      - "${CALENDAR_GRPC_PORT}:${CALENDAR_GRPC_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
      CALENDAR_HTTP_PORT: ${CALENDAR_HTTP_PORT}
      CALENDAR_GRPC_PORT: ${CALENDAR_GRPC_PORT}
    volumes:
      - ./config.calendar.yaml:/etc/calendar/config.yaml

  tests:
    build:
      context: ..
      dockerfile: build/Dockerfile.tests
    depends_on:
      calendar:
        condition: service_started
    environment:
      DB_CONN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}"
      CALENDAR_HOST: calendar
      CALENDAR_HTTP_PORT: ${CALENDAR_HTTP_PORT}

volumes:
  postgres_test_data: