logger:
  level: "INFO"

server:
  addr: "localhost:8080"

grpc:
  addr: "localhost:9090"

storage:
  type: "MEMORY"

rabbitmq:
  addr: "localhost:5672"
  queue: "calendar_events"
  username: "guest"
  password: "guest"
