{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    {{- include "calendar.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- if .ports }}
          ports:
            {{- range $name, $port := .ports }}
            - containerPort: {{ $port }}
              name: {{ $name }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /run/config.yaml
              subPath: config.yaml
          command: ["/app/{{ .name }}"]
          args: ["-config", "/run/config.yaml"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: {{ .name }}-config
{{- end }}